swagger: '2.0'
info:
  title: NL Photo Album
  description: 'Using user text/voice input, search or index photos'
  version: 1.0.0
schemes:
  - https
basePath: /v1
produces:
  - application/json
paths:
  /photos:
    put:
      summary: The endpoint indexing user given photos.
      description: |
        This API takes in one image with an option to tag with custom labels.
      # tags:
        - NLU
      # operationId: sendMessage
      produces:
        - application/json
      consumes:
         - multipart/form-data
      parameters:
        - in: formData
          name: upfile
          type: file
          required: true
          description: File to upload.
          # schema:
          #   $ref: '#/definitions/PhotosRequest'
        - in: formData
          name: labels
          type: string
          required: false
          description: Custom labels.
      responses:
        '200':
          description: A Photo upload response
          schema:
            type: object
            properties:
              success:
                type: bool
                description: Success or failure
              message:
                type: string
                description: details of indexing
            # $ref: '#/definitions/PhotosResponse'
        '403':
          description: Unauthorized
          # schema:
          #   $ref: '#/definitions/Error'
        '500':
          description: Unexpected error
          # schema:
          #   $ref: '#/definitions/Error'
# definitions:
  # PhotosRequest:
  #   type: object
  #   properties:
  #     messages:
  #       type: array
  #       items:
  #         $ref: '#/definitions/Message'
  # PhotosResponse:
  #   type: object
  #   properties:
  #     messages:
  #       type: array
  #       items:
  #         $ref: '#/definitions/Message'
  # Message:
  #   type: object
  #   properties:
  #     type:
  #       type: string
  #     unstructured:
  #       $ref: '#/definitions/UnstructuredMessage'
  # UnstructuredMessage:
  #   type: object
  #   properties:
  #     id:
  #       type: string
  #     text:
  #       type: string
  #     timestamp:
  #       type: string
  #       format: datetime
  # Error:
  #   type: object
  #   properties:
  #     code:
  #       type: integer
  #       format: int32
  #     message:
  #       type: string